### PR TITLE
Add EnumCodec

### LINKED ISSUE #33: Add EnumCodec
When trying to save an object that contains an `enum` value, I got the following error:

```
java.lang.IllegalArgumentException: Cannot encode [MY_VALUE] parameter of type [com.mycompany.MyEnum]
	at io.r2dbc.mssql.codec.DefaultCodecs.encode(DefaultCodecs.java:92) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at io.r2dbc.mssql.PreparedMssqlStatement.bind(PreparedMssqlStatement.java:155) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at io.r2dbc.mssql.PreparedMssqlStatement.bind(PreparedMssqlStatement.java:57) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at org.springframework.data.r2dbc.dialect.NamedBindMarkers$NamedBindMarker.bind(NamedBindMarkers.java:105) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy$DefaultBindableInsert.bind(DefaultReactiveDataAccessStrategy.java:465) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.BindableOperation.bind(BindableOperation.java:53) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$2(DefaultDatabaseClient.java:996) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$3(DefaultDatabaseClient.java:1002) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$2.apply(DefaultSqlResult.java:81) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$2.apply(DefaultSqlResult.java:78) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.doInConnectionMany(DefaultDatabaseClient.java:1018) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.lambda$inConnectionMany$2(DefaultDatabaseClient.java:159) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
```

There is no EnumCodec yet, but once implemented it should look like the one from postgresql: https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/EnumCodec.java

Interestingly decoding of `varchar` to an `enum` value works. It is decoded to a `String` and Springs `ConversionService` turns it into an `enum` value.

I would have added a codec by myself, but there is no easy way to add a custom codec to `DefaultCodecs`.

### PR DESCRIPTION
**Pull request by essentinal**
For now I suggest to add a simple EnumCodec, since it solves my issue.
Fixes #33

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@essentinal Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-mssql&pullRequestId=34)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-mssql&pullRequestId=34) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@essentinal Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-mssql&pullRequestId=34)!

**Comment by mp911de** [comment]
Looks good from a cursory review. We should not add any other functionality beyond that. Using an `enum` and deciding how it should be represented in the database is an application-specific decision. Providing this feature at driver level is only a convenience feature and actually, this decision should be handled in a client.

**Comment by gregturn** [comment]
If we do this here, it seems like we'd need the same thing in every r2dbc driver. The purpose of this is to translate a Java `enum` from/to an `int` or a `String`.

Frankly, this sounds like a feature better implemented at the client level (`spring-data-r2dbc`, etc.) Once done, it works for ALL drivers, including those not even implemented yet.

Whether such a feature on the client level would require any SPI changes, I'm not sure I see that (yet).

**Comment by mp911de** [comment]
Reiterating on that topic, I'm also inclined to not provide an enum codec. If we would include that type of codecs in all drivers, then we would basically expect all drivers to ship with an enum codec to reduce variance amongst vendor-specifics. With R2DBC we intend to reduce the number of things each driver has to implement and enum codec falls in that category which would be provided by a driver with the same mapping (`Enum` to `String` and vice versa) while this is not a protocol-specific feature.

@nebhale Thoughts?

**Comment by mp911de** [comment]
We discussed this topic in our team and concluded that enum support is a application-specific feature that would be implemented in the driver. Drivers only encapsulate database-specific feature. Mapping an enum name to a character column is not database-specific but rather an opinionated convenience feature.

Therefore, we decided to not include `EnumCodec` in our project. We could consider exposing a configurable codec registry so these concerns can be added through a specific extension point.

Thanks for all your effort!

**Comment by alpeshjikadra** [comment]
Which maven version has this bug fixes ?

**Comment by mp911de** [comment]
Enum codecs are not supported as per comment in this ticket.

**Pull request closed without merging**
